### ISSUE TITLE
code for read posts?

### ISSUE THREAD

**Issue by UmutAlihan** [ihfazhillah/facebook#1]
Is it possible to read the posts on my wall and post a status accordingly as a response?

**Comment by ihfazhillah** [comment]
what do you mean with a "response"?

**Comment by ihfazhillah** [comment]
i think, its not possible. the script what i made is just a simple status
poster. not other.

**Comment by UmutAlihan** [comment]
sorry for my bad english

thank you for your code I am using it now to automatically post status updates.

If other people write and posts on my wall I want to my code be able to sense it and answer as a comment on that post by mentioning the person...

If I can develop something like that Im going to contribute your code

**Comment by ihfazhillah** [comment]
glad to hear that,

ahaa, i see what you mean. unfortunately, you can do that with my code. you
can code it your self, or mybe you can hire me.  :)
