### ISSUE TITLE
recent error on execution

### ISSUE THREAD

**Issue by UmutAlihan** [ihfazhillah/facebook#2]
I started to get this error:
line 43, in post_status
    form = soup.select(COMPOSER_SELECTOR)[0]
IndexError: list index out of range

Do you think Facebook might be changing its mobile site architecture?

Thank you by the way for your nice script. Since today I utilized it a lot. Great work!

**Comment by ihfazhillah** [comment]
Maybe, I'll check it later

**Comment by ihfazhillah** [comment]
need additional step to reach timeline feed: 
1. get this url `/login/save-device/cancel/?ref=dbl`
if this url found

and change `COMPOSER_SELECTOR`  into `#mbasic_inline_feed_composer`

i will change later when i have free time.

Thank you for reporting this issue

**Comment by ihfazhillah** [comment]
Problem Solved, and there a new API to access this script. Check it out on README

**Comment by UmutAlihan** [comment]
Excuse me for my late repsonse. Since I work in a company I have very little time to code stuff..

I have implemented your new version of script.

It works flawlessly. Thank you, thank you, thank you!
